# Flash programmer parameters file
# Automatically generated by SDK (26/02/2016 00:51:03).

set FLASH_FILE                    "E:/Microblaze/Software/ANN_Heartbeat_Sorter/Release/ANN_Heartbeat_Sorter.elf"
set FLASH_BASEADDR                0x89000000
set FLASH_PROG_OFFSET             0x00060000
set FLASH_BUSWIDTH                8
set SCRATCH_BASEADDR              0x8C000000
set SCRATCH_LEN                   0x04000000
set TARGET_TYPE                   "MICROBLAZE"
set PROC_INSTANCE                 "microblaze_0"
set EXTRA_COMPILER_FLAGS          "-mxl-barrel-shift -mno-xl-soft-mul "
set XMD_CONNECT                   "connect mb mdm  -debugdevice cpunr 1"
set XILINX_PLATFORM_FLASH         1
set ENDIANNESS                    "BE"
